### ISSUE TITLE
Adapt write_spice function to create JSON-LD file

### ISSUE THREAD

**Issue by yashdubey132** [openwashdata/washr#30]
The metadata generated from washr defaults is richer in detail than data_spice default. Will need to adapt write_spice or create our own function to convert to JSON-LD 

Perhaps something like `write_metadata_json`

**Comment by yashdubey132** [comment]
This may not be required (or useful) as our data is not exchanged between websites. See the purpose of JSON-LD here: https://www.youtube.com/watch?v=vioCbTo3C-4

**Comment by larnsce** [comment]
But, I think Google Data and search engines can pick up on JSON-LD better. If it's low effort to implement the function, I would still do it and then think about where the data can be shared for maximum visbility.

**Comment by yashdubey132** [comment]
Added this functionality in latest commit: https://github.com/openwashdata/washr/commit/ff215ea897b91fff8ee9e43b8e52764ee87a454d

**Comment by larnsce** [comment]
Great work. I can see the effort you have put into preparing these functions. They will be very useful for us.
