### ISSUE TITLE
Release washr 0.0.1

### ISSUE THREAD

**Issue by mianzg** [openwashdata/washr#8]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [ ] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ] `usethis::use_news_md()`

**Comment by mianzg** [comment]
@larnsce Who will be the copyright holder (role 'cph')?

**Comment by larnsce** [comment]
@mianzg

> Who will be the copyright holder (role 'cph')?

Global Health Engineering, ETH Zurich

**Comment by mianzg** [comment]
- [ ] omit the redundant "R" at the start of your title.
- [ ] references describing the methods in your package? what if we do not have
- [ ] single quotes package names, software and API.  e.g. 'openwashdata'
- [ ] return documentation of update_citation.R
- [ ] remove console print of update_citation.R
- [ ] do not write by default or in your examples/vignettes/tests in the user's home filespace (including the package directory and getwd()). This is not allowed by CRAN policies. Please omit any default path in writing functions. In your examples/vignettes/tests you can write to tempdir().

**Comment by mianzg** [comment]
@larnsce 

>  references describing the methods in your package? what if we do not have

We haven't published the workflow on the website. Should I just communicate that we do not have anything.

> single quotes package names, software and API. e.g. 'openwashdata'

Explain this is not a software?

**Comment by larnsce** [comment]
Yes, go ahead and communicate to them what you suggest.

**Comment by larnsce** [comment]
@bonschorno: I have assigned this issue to you. Could you complete this?

**Comment by bonschorno** [comment]
Opened a new issue for the updated CRAN release.
